site_name: CS61BL Guide

repo_name: twangodev/cs61bl-guide
repo_url: https://github.com/twangodev/cs61bl-guide
edit_uri: edit/main/docs/

site_url: https://cs61bl.twango.dev/
site_description: A handy guide and reference for CS61BL students.

nav:
  - Home: index.md
  - Exam Preparation:
    - Topical Resources: exam-prep/topical-resources.md
  - Concepts:
    - Object Oriented Programming:
      - Inheritance: concepts/oop/inheritance.md
      - Dynamic Method Selection: concepts/oop/dynamic-method-selection.md
    - Hashing: concepts/hashing.md
    - Persistence: concepts/persistence.md

  - Data Structures:
    - Trees:
      - Binary Trees: data-structures/trees/binary-trees.md
      - Binary Search Trees: data-structures/trees/binary-search-trees.md
      - Left Leaning Red Black Trees: data-structures/trees/left-leaning-red-black-trees.md
  - Sorting:
      - Insertion Sort: sorting/insertion-sort.md

theme:
  name: material
  logo: assets/cs61bl.png
  favicon: assets/favicon.png
  features:
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
    - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - glightbox
  - offline
  - social

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true


extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css